# Generated by Django 2.2.3 on 2020-12-20 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='test',
            table='tableName',
        ),
    ]
