# Generated by Django 2.2.3 on 2021-01-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20201220_0705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='testTable',
        ),
    ]
