# Generated by Django 2.2.3 on 2021-01-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20210109_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='./images')),
            ],
        ),
        migrations.DeleteModel(
            name='testTable',
        ),
    ]
