# Generated by Django 2.2.3 on 2021-01-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_auto_20210109_0926'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageManager',
        ),
    ]
